//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vueling.Presentation.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rebel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Rebel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _planetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string _name {
            get {
                return this._nameField;
            }
            set {
                if ((object.ReferenceEquals(this._nameField, value) != true)) {
                    this._nameField = value;
                    this.RaisePropertyChanged("_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string _planet {
            get {
                return this._planetField;
            }
            set {
                if ((object.ReferenceEquals(this._planetField, value) != true)) {
                    this._planetField = value;
                    this.RaisePropertyChanged("_planet");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.WebServiceSoap")]
    public interface WebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Create", ReplyAction="*")]
        bool Create();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Create", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> CreateAsync();
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento rebel del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        Vueling.Presentation.ServiceReference.AddResponse Add(Vueling.Presentation.ServiceReference.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<Vueling.Presentation.ServiceReference.AddResponse> AddAsync(Vueling.Presentation.ServiceReference.AddRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento rebel del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetById", ReplyAction="*")]
        Vueling.Presentation.ServiceReference.GetByIdResponse GetById(Vueling.Presentation.ServiceReference.GetByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetById", ReplyAction="*")]
        System.Threading.Tasks.Task<Vueling.Presentation.ServiceReference.GetByIdResponse> GetByIdAsync(Vueling.Presentation.ServiceReference.GetByIdRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetAllResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAll", ReplyAction="*")]
        Vueling.Presentation.ServiceReference.GetAllResponse GetAll(Vueling.Presentation.ServiceReference.GetAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAll", ReplyAction="*")]
        System.Threading.Tasks.Task<Vueling.Presentation.ServiceReference.GetAllResponse> GetAllAsync(Vueling.Presentation.ServiceReference.GetAllRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento rebel del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        Vueling.Presentation.ServiceReference.UpdateResponse Update(Vueling.Presentation.ServiceReference.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<Vueling.Presentation.ServiceReference.UpdateResponse> UpdateAsync(Vueling.Presentation.ServiceReference.UpdateRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento rebel del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        Vueling.Presentation.ServiceReference.DeleteResponse Delete(Vueling.Presentation.ServiceReference.DeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<Vueling.Presentation.ServiceReference.DeleteResponse> DeleteAsync(Vueling.Presentation.ServiceReference.DeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteAll", ReplyAction="*")]
        bool DeleteAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteAll", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteAllAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add", Namespace="http://tempuri.org/", Order=0)]
        public Vueling.Presentation.ServiceReference.AddRequestBody Body;
        
        public AddRequest() {
        }
        
        public AddRequest(Vueling.Presentation.ServiceReference.AddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Vueling.Presentation.ServiceReference.Rebel rebel;
        
        public AddRequestBody() {
        }
        
        public AddRequestBody(Vueling.Presentation.ServiceReference.Rebel rebel) {
            this.rebel = rebel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddResponse", Namespace="http://tempuri.org/", Order=0)]
        public Vueling.Presentation.ServiceReference.AddResponseBody Body;
        
        public AddResponse() {
        }
        
        public AddResponse(Vueling.Presentation.ServiceReference.AddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddResult;
        
        public AddResponseBody() {
        }
        
        public AddResponseBody(bool AddResult) {
            this.AddResult = AddResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetById", Namespace="http://tempuri.org/", Order=0)]
        public Vueling.Presentation.ServiceReference.GetByIdRequestBody Body;
        
        public GetByIdRequest() {
        }
        
        public GetByIdRequest(Vueling.Presentation.ServiceReference.GetByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Vueling.Presentation.ServiceReference.Rebel rebel;
        
        public GetByIdRequestBody() {
        }
        
        public GetByIdRequestBody(Vueling.Presentation.ServiceReference.Rebel rebel) {
            this.rebel = rebel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public Vueling.Presentation.ServiceReference.GetByIdResponseBody Body;
        
        public GetByIdResponse() {
        }
        
        public GetByIdResponse(Vueling.Presentation.ServiceReference.GetByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Vueling.Presentation.ServiceReference.Rebel GetByIdResult;
        
        public GetByIdResponseBody() {
        }
        
        public GetByIdResponseBody(Vueling.Presentation.ServiceReference.Rebel GetByIdResult) {
            this.GetByIdResult = GetByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAll", Namespace="http://tempuri.org/", Order=0)]
        public Vueling.Presentation.ServiceReference.GetAllRequestBody Body;
        
        public GetAllRequest() {
        }
        
        public GetAllRequest(Vueling.Presentation.ServiceReference.GetAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllRequestBody {
        
        public GetAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public Vueling.Presentation.ServiceReference.GetAllResponseBody Body;
        
        public GetAllResponse() {
        }
        
        public GetAllResponse(Vueling.Presentation.ServiceReference.GetAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Vueling.Presentation.ServiceReference.Rebel[] GetAllResult;
        
        public GetAllResponseBody() {
        }
        
        public GetAllResponseBody(Vueling.Presentation.ServiceReference.Rebel[] GetAllResult) {
            this.GetAllResult = GetAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public Vueling.Presentation.ServiceReference.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(Vueling.Presentation.ServiceReference.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Vueling.Presentation.ServiceReference.Rebel rebel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string newName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string newPlanet;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(Vueling.Presentation.ServiceReference.Rebel rebel, string newName, string newPlanet) {
            this.rebel = rebel;
            this.newName = newName;
            this.newPlanet = newPlanet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public Vueling.Presentation.ServiceReference.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(Vueling.Presentation.ServiceReference.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateResult;
        
        public UpdateResponseBody() {
        }
        
        public UpdateResponseBody(bool UpdateResult) {
            this.UpdateResult = UpdateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete", Namespace="http://tempuri.org/", Order=0)]
        public Vueling.Presentation.ServiceReference.DeleteRequestBody Body;
        
        public DeleteRequest() {
        }
        
        public DeleteRequest(Vueling.Presentation.ServiceReference.DeleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Vueling.Presentation.ServiceReference.Rebel rebel;
        
        public DeleteRequestBody() {
        }
        
        public DeleteRequestBody(Vueling.Presentation.ServiceReference.Rebel rebel) {
            this.rebel = rebel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public Vueling.Presentation.ServiceReference.DeleteResponseBody Body;
        
        public DeleteResponse() {
        }
        
        public DeleteResponse(Vueling.Presentation.ServiceReference.DeleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DeleteResult;
        
        public DeleteResponseBody() {
        }
        
        public DeleteResponseBody(bool DeleteResult) {
            this.DeleteResult = DeleteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : Vueling.Presentation.ServiceReference.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Vueling.Presentation.ServiceReference.WebServiceSoap>, Vueling.Presentation.ServiceReference.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Create() {
            return base.Channel.Create();
        }
        
        public System.Threading.Tasks.Task<bool> CreateAsync() {
            return base.Channel.CreateAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vueling.Presentation.ServiceReference.AddResponse Vueling.Presentation.ServiceReference.WebServiceSoap.Add(Vueling.Presentation.ServiceReference.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public bool Add(Vueling.Presentation.ServiceReference.Rebel rebel) {
            Vueling.Presentation.ServiceReference.AddRequest inValue = new Vueling.Presentation.ServiceReference.AddRequest();
            inValue.Body = new Vueling.Presentation.ServiceReference.AddRequestBody();
            inValue.Body.rebel = rebel;
            Vueling.Presentation.ServiceReference.AddResponse retVal = ((Vueling.Presentation.ServiceReference.WebServiceSoap)(this)).Add(inValue);
            return retVal.Body.AddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vueling.Presentation.ServiceReference.AddResponse> Vueling.Presentation.ServiceReference.WebServiceSoap.AddAsync(Vueling.Presentation.ServiceReference.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vueling.Presentation.ServiceReference.AddResponse> AddAsync(Vueling.Presentation.ServiceReference.Rebel rebel) {
            Vueling.Presentation.ServiceReference.AddRequest inValue = new Vueling.Presentation.ServiceReference.AddRequest();
            inValue.Body = new Vueling.Presentation.ServiceReference.AddRequestBody();
            inValue.Body.rebel = rebel;
            return ((Vueling.Presentation.ServiceReference.WebServiceSoap)(this)).AddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vueling.Presentation.ServiceReference.GetByIdResponse Vueling.Presentation.ServiceReference.WebServiceSoap.GetById(Vueling.Presentation.ServiceReference.GetByIdRequest request) {
            return base.Channel.GetById(request);
        }
        
        public Vueling.Presentation.ServiceReference.Rebel GetById(Vueling.Presentation.ServiceReference.Rebel rebel) {
            Vueling.Presentation.ServiceReference.GetByIdRequest inValue = new Vueling.Presentation.ServiceReference.GetByIdRequest();
            inValue.Body = new Vueling.Presentation.ServiceReference.GetByIdRequestBody();
            inValue.Body.rebel = rebel;
            Vueling.Presentation.ServiceReference.GetByIdResponse retVal = ((Vueling.Presentation.ServiceReference.WebServiceSoap)(this)).GetById(inValue);
            return retVal.Body.GetByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vueling.Presentation.ServiceReference.GetByIdResponse> Vueling.Presentation.ServiceReference.WebServiceSoap.GetByIdAsync(Vueling.Presentation.ServiceReference.GetByIdRequest request) {
            return base.Channel.GetByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vueling.Presentation.ServiceReference.GetByIdResponse> GetByIdAsync(Vueling.Presentation.ServiceReference.Rebel rebel) {
            Vueling.Presentation.ServiceReference.GetByIdRequest inValue = new Vueling.Presentation.ServiceReference.GetByIdRequest();
            inValue.Body = new Vueling.Presentation.ServiceReference.GetByIdRequestBody();
            inValue.Body.rebel = rebel;
            return ((Vueling.Presentation.ServiceReference.WebServiceSoap)(this)).GetByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vueling.Presentation.ServiceReference.GetAllResponse Vueling.Presentation.ServiceReference.WebServiceSoap.GetAll(Vueling.Presentation.ServiceReference.GetAllRequest request) {
            return base.Channel.GetAll(request);
        }
        
        public Vueling.Presentation.ServiceReference.Rebel[] GetAll() {
            Vueling.Presentation.ServiceReference.GetAllRequest inValue = new Vueling.Presentation.ServiceReference.GetAllRequest();
            inValue.Body = new Vueling.Presentation.ServiceReference.GetAllRequestBody();
            Vueling.Presentation.ServiceReference.GetAllResponse retVal = ((Vueling.Presentation.ServiceReference.WebServiceSoap)(this)).GetAll(inValue);
            return retVal.Body.GetAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vueling.Presentation.ServiceReference.GetAllResponse> Vueling.Presentation.ServiceReference.WebServiceSoap.GetAllAsync(Vueling.Presentation.ServiceReference.GetAllRequest request) {
            return base.Channel.GetAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vueling.Presentation.ServiceReference.GetAllResponse> GetAllAsync() {
            Vueling.Presentation.ServiceReference.GetAllRequest inValue = new Vueling.Presentation.ServiceReference.GetAllRequest();
            inValue.Body = new Vueling.Presentation.ServiceReference.GetAllRequestBody();
            return ((Vueling.Presentation.ServiceReference.WebServiceSoap)(this)).GetAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vueling.Presentation.ServiceReference.UpdateResponse Vueling.Presentation.ServiceReference.WebServiceSoap.Update(Vueling.Presentation.ServiceReference.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public bool Update(Vueling.Presentation.ServiceReference.Rebel rebel, string newName, string newPlanet) {
            Vueling.Presentation.ServiceReference.UpdateRequest inValue = new Vueling.Presentation.ServiceReference.UpdateRequest();
            inValue.Body = new Vueling.Presentation.ServiceReference.UpdateRequestBody();
            inValue.Body.rebel = rebel;
            inValue.Body.newName = newName;
            inValue.Body.newPlanet = newPlanet;
            Vueling.Presentation.ServiceReference.UpdateResponse retVal = ((Vueling.Presentation.ServiceReference.WebServiceSoap)(this)).Update(inValue);
            return retVal.Body.UpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vueling.Presentation.ServiceReference.UpdateResponse> Vueling.Presentation.ServiceReference.WebServiceSoap.UpdateAsync(Vueling.Presentation.ServiceReference.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vueling.Presentation.ServiceReference.UpdateResponse> UpdateAsync(Vueling.Presentation.ServiceReference.Rebel rebel, string newName, string newPlanet) {
            Vueling.Presentation.ServiceReference.UpdateRequest inValue = new Vueling.Presentation.ServiceReference.UpdateRequest();
            inValue.Body = new Vueling.Presentation.ServiceReference.UpdateRequestBody();
            inValue.Body.rebel = rebel;
            inValue.Body.newName = newName;
            inValue.Body.newPlanet = newPlanet;
            return ((Vueling.Presentation.ServiceReference.WebServiceSoap)(this)).UpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vueling.Presentation.ServiceReference.DeleteResponse Vueling.Presentation.ServiceReference.WebServiceSoap.Delete(Vueling.Presentation.ServiceReference.DeleteRequest request) {
            return base.Channel.Delete(request);
        }
        
        public bool Delete(Vueling.Presentation.ServiceReference.Rebel rebel) {
            Vueling.Presentation.ServiceReference.DeleteRequest inValue = new Vueling.Presentation.ServiceReference.DeleteRequest();
            inValue.Body = new Vueling.Presentation.ServiceReference.DeleteRequestBody();
            inValue.Body.rebel = rebel;
            Vueling.Presentation.ServiceReference.DeleteResponse retVal = ((Vueling.Presentation.ServiceReference.WebServiceSoap)(this)).Delete(inValue);
            return retVal.Body.DeleteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vueling.Presentation.ServiceReference.DeleteResponse> Vueling.Presentation.ServiceReference.WebServiceSoap.DeleteAsync(Vueling.Presentation.ServiceReference.DeleteRequest request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vueling.Presentation.ServiceReference.DeleteResponse> DeleteAsync(Vueling.Presentation.ServiceReference.Rebel rebel) {
            Vueling.Presentation.ServiceReference.DeleteRequest inValue = new Vueling.Presentation.ServiceReference.DeleteRequest();
            inValue.Body = new Vueling.Presentation.ServiceReference.DeleteRequestBody();
            inValue.Body.rebel = rebel;
            return ((Vueling.Presentation.ServiceReference.WebServiceSoap)(this)).DeleteAsync(inValue);
        }
        
        public bool DeleteAll() {
            return base.Channel.DeleteAll();
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAllAsync() {
            return base.Channel.DeleteAllAsync();
        }
    }
}
